### ISSUE TITLE
use of library

### ISSUE THREAD

**Issue by GriffithWhiteHawk** [engineertype/MAX31855#1]
I have intalled and uploaded the MAX31855x8 librabry provided and everytime I use the code given I get an error upon using verify. 
I am quite new to arduino and using the MAX31855x8 with my Arduino UNO.
Please help me to understand what I am doing wrong.
  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
Arduino: 1.0.6 (Windows 7), Board: "Arduino Uno"
In file included from C:\Users\Griffith\Desktop\Arduino\Arduino\hardware\arduino\cores\arduino/Arduino.h:235,
                 from MAX31855x8.ino:58:
C:\Users\Griffith\Desktop\Arduino\Arduino\hardware\arduino\variants\standard/pins_arduino.h:42: error: expected unqualified-id before numeric constant
C:\Users\Griffith\Desktop\Arduino\Arduino\hardware\arduino\variants\standard/pins_arduino.h:43: error: expected unqualified-id before numeric constant
MAX31855x8:58: error: 'MAX31855' does not name a type
MAX31855x8.ino: In function 'void loop()':
MAX31855x8:80: error: 'temp' was not declared in this scope
MAX31855x8:80: error: 'CELSIUS' was not declared in this scope
MAX31855x8:95: error: 'FAULT_OPEN' was not declared in this scope
MAX31855x8.ino: In function 'void printTemperature(double)':
MAX31855x8:110: error: 'FAULT_OPEN' was not declared in this scope
MAX31855x8:113: error: 'FAULT_SHORT_GND' was not declared in this scope
MAX31855x8:116: error: 'FAULT_SHORT_VCC' was not declared in this scope
MAX31855x8:119: error: 'NO_MAX31855' was not declared in this scope

**Comment by engineertype** [comment]
Hi,

You have not installed the library.  Please follow this guide:

http://arduino.cc/en/Guide/Libraries

Regards,

Peter

On Thu, Jan 22, 2015 at 5:37 PM, GriffithWhiteHawk <notifications@github.com

**Comment by GriffithWhiteHawk** [comment]
Thank you for the quick response.  I followed the instructions for automatic install of the library.
it shows up on my Arduino 1.0.6 list.  I click import library, my screen blinks then there is nothing.  so i go to file,  and open the example then click import library and I still recieve the same errors upon clicking verify.

**Comment by GriffithWhiteHawk** [comment]
Thank you Peter.  
that was very helpful.  I appreciate you helping a noob out

**Comment by GriffithWhiteHawk** [comment]
Here's a new one.   I want to use individual thermo readings to control relays.   How would I go about selecting an individual thermocouple to turn activate and deactivate a relay?

**Comment by engineertype** [comment]
Hi,

This isn't the correct place for general Arduino questions.  You'll get
better help from the Arduino forums:
http://forum.arduino.cc/

Regards,

Peter

On Fri, Jan 23, 2015 at 2:59 AM, GriffithWhiteHawk <notifications@github.com
